title   TelemetryOS Edge
sort-key tos-0
linux   /vmlinuz-linux
initrd  /initramfs-linux.img
options root=UUID=032f90b1-d19f-4a11-92ce-51100cea9c96 rw quiet splash fsck.mode=force fsck.repair=yes audit=0 elevator=none rootflags=noatime,commit=600 noresume
